name: Build

on:
  push:
    branches:
      - development

jobs:
  build:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'josippapez' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build
        if: matrix.os == 'ubuntu-latest'
        env:
          # These values are used for auto updates signing
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          npm run build
