name: 'Deploy: Development'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.2.0
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          scope: ${{ secrets.VERCEL_ORGANIZATION_ID}} # Needed for team deployment
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          vercel-args: '--confirm' #Optional

