name: 'Deploy: Production'

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.2.0
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID}} #Required
          vercel-args: '--prod --confirm' #Optional
          scope: ${{ secrets.VERCEL_ORGANIZATION_ID}} # Needed for team deployment
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
